//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public string Tittle { get; set; }
        public string Director { get; set; }
        public string Genre { get; set; }
        public string Runtime { get; set; }
        public string RealeseDate { get; set; }
    }
}
